### ISSUE TITLE
Изменить стили для Balloon (подсказки) - 

### ISSUE THREAD

**Issue by Manimall** [gribnoysup/react-yandex-maps#315]
рабочий сандбокс - https://codesandbox.io/s/cant-style-balloon-99b2f?file=/src/data.ts
и вопрос относящийся к ишью - https://qna.habr.com/q/901581 - на этотвопрос пока нет ответа.

получается стилизовать контент, который входит в сам балун, а хотелось бы так же изменить фон обертку и отступы у обертки балуна

**Comment by mmarkelov** [comment]
@Manimall самый простой вариант использовать css:
```css
ymaps[class$="balloon__content"] {
  background: red;
}

ymaps[class$="balloon__layout"] {
  padding: 5px;
  background: red;
}

ymaps[class$="balloon__tail"]::after {
  background: red;
}
```
